name: Setup Animated Java Exports
description: >
  Attempts to restore Animated Java export files from cache.
  If cache not hit, installs Animated Java and runs our auto-exporter

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-yarn
    - uses: actions/cache/restore@v4
      id: cache-animated-java-exports
      with:
        key: cache-animated-java-exports-${{ env.BLOCKBENCH_URL }}-${{ env.ANIMATED_JAVA_URL }}-${{ hashFiles('resourcepack/assets/omega-flowey/models/**/*.ajblueprint')}}
        restore-keys: cache-animated-java-exports-${{ env.BLOCKBENCH_URL }}-${{ env.ANIMATED_JAVA_URL }}-
        path: |
          datapacks/animated_java/data
          datapacks/animated_java/data.ajmeta
          resourcepack/assets.ajmeta
          resourcepack/assets/animated_java
          resourcepack/assets/minecraft/models/item/pink_dye.json
          resourcepack/assets/omega-flowey/models/last_exported_hashes.json
    - run: bash ${{ github.action_path }}/install-animated-java-and-run-auto-exporter.sh
      if: ${{ steps.cache-animated-java-exports.outputs.cache-hit != 'true' }}
      shell: bash
    - uses: actions/cache/save@v4
      if: ${{ steps.cache-animated-java-exports.outputs.cache-hit != 'true' }}
      with:
        key: ${{ steps.cache-animated-java-exports.outputs.cache-primary-key }}
        path: |
          datapacks/animated_java/data
          datapacks/animated_java/data.ajmeta
          resourcepack/assets.ajmeta
          resourcepack/assets/animated_java
          resourcepack/assets/minecraft/models/item/pink_dye.json
          resourcepack/assets/omega-flowey/models/last_exported_hashes.json
