name: datapack

on: [push]

env:
  ANIMATED_JAVA_URL: https://github.com/Animated-Java/animated-java/releases/download/v1.10.0-beta.7/animated_java.js
  BLOCKBENCH_URL: https://github.com/JannisX11/blockbench/releases/download/v5.1.4/Blockbench_5.1.4.deb
  FABRIC_API: https://cdn.modrinth.com/data/P7dR8mSH/versions/fm7UYECV/fabric-api-0.145.4%2B26.1.2.jar
  FABRIC_SERVER: https://meta.fabricmc.net/v2/versions/loader/26.1.2/0.19.1/1.1.1/server/jar
  PACKTEST: https://cdn.modrinth.com/data/XsKUhp45/versions/MGLOzSvz/packtest-2.5.0.jar

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
      - name: Run lint scripts on datapacks
        run: yarn start lint.custom.datapacks
        env:
          FORCE_COLOR: 2

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup-animated-java-exports
  #       timeout-minutes: 4
  #     - run: echo "$(cat blockbench.log)"
  #       if: ${{ failure() || cancelled() }}
  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '25'
  #     - name: Download server files
  #       run: |
  #         curl -o server.jar $FABRIC_SERVER
  #         mkdir mods
  #         curl -o mods/fabric-api.jar $FABRIC_API
  #         curl -o mods/packtest.jar $PACKTEST
  #     - name: Copy packs to world
  #       run: |
  #         mkdir -p world
  #         cp -r datapacks world
  #     - name: Run test server
  #       run: |
  #         java -Xmx2G -Dpacktest.auto -Dpacktest.auto.annotations -Dpacktest.auto.coloring -jar server.jar nogui
